const fs = require('fs');
const execSync = require('child_process').execSync;

let commitHash = 'unknown';
try {
  commitHash = execSync('git rev-parse --short HEAD').toString().trim();
} catch (e) {
  console.warn('Failed to get git commit hash, using "unknown"', e);
}

const content = `// This file is auto-generated by scripts/git-version.js
export const gitCommit = '${commitHash}';
`;

fs.writeFileSync('src/environments/version.ts', content);
console.log(`[git-version] Successfully generated version.ts with commit hash: ${commitHash}`);
